import { SYNC_STATE, SyncState } from './enums';

// Allowed transitions for the registration sync-state machine. Any transition
// not listed here is rejected (and logged). Terminal-ish states can always be
// re-queued (a new poll cycle) so most states allow → QUEUED.
const TRANSITIONS: Record<string, SyncState[]> = {
  PENDING: [SYNC_STATE.QUEUED, SYNC_STATE.MANUAL_REVIEW, SYNC_STATE.STALE],
  QUEUED: [SYNC_STATE.SYNCING_STATUS, SYNC_STATE.SYNCING_RESULTS, SYNC_STATE.MANUAL_REVIEW, SYNC_STATE.RATE_LIMITED, SYNC_STATE.RETRY_SCHEDULED, SYNC_STATE.STALE],
  SYNCING_STATUS: [
    SYNC_STATE.STATUS_SYNCED, SYNC_STATE.NOT_FOUND, SYNC_STATE.AUTH_FAILED, SYNC_STATE.API_ERROR,
    SYNC_STATE.TIMEOUT, SYNC_STATE.RATE_LIMITED, SYNC_STATE.RETRY_SCHEDULED, SYNC_STATE.MANUAL_REVIEW,
  ],
  STATUS_SYNCED: [SYNC_STATE.SYNCING_RESULTS, SYNC_STATE.COMPLETED, SYNC_STATE.QUEUED, SYNC_STATE.STALE],
  SYNCING_RESULTS: [
    SYNC_STATE.RESULTS_SYNCED, SYNC_STATE.NOT_FOUND, SYNC_STATE.AUTH_FAILED, SYNC_STATE.API_ERROR,
    SYNC_STATE.TIMEOUT, SYNC_STATE.RATE_LIMITED, SYNC_STATE.RETRY_SCHEDULED, SYNC_STATE.MANUAL_REVIEW,
  ],
  RESULTS_SYNCED: [SYNC_STATE.COMPLETED, SYNC_STATE.QUEUED, SYNC_STATE.STALE],
  COMPLETED: [SYNC_STATE.QUEUED, SYNC_STATE.STALE], // may re-poll (e.g. re-open)
  NOT_FOUND: [SYNC_STATE.QUEUED, SYNC_STATE.RETRY_SCHEDULED, SYNC_STATE.MANUAL_REVIEW],
  AUTH_FAILED: [SYNC_STATE.QUEUED, SYNC_STATE.RETRY_SCHEDULED, SYNC_STATE.MANUAL_REVIEW],
  API_ERROR: [SYNC_STATE.QUEUED, SYNC_STATE.RETRY_SCHEDULED, SYNC_STATE.MANUAL_REVIEW],
  TIMEOUT: [SYNC_STATE.QUEUED, SYNC_STATE.RETRY_SCHEDULED, SYNC_STATE.MANUAL_REVIEW],
  RATE_LIMITED: [SYNC_STATE.QUEUED, SYNC_STATE.RETRY_SCHEDULED],
  RETRY_SCHEDULED: [SYNC_STATE.QUEUED, SYNC_STATE.SYNCING_STATUS, SYNC_STATE.SYNCING_RESULTS, SYNC_STATE.MANUAL_REVIEW],
  MANUAL_REVIEW: [SYNC_STATE.QUEUED], // operator re-queues
  STALE: [SYNC_STATE.QUEUED, SYNC_STATE.MANUAL_REVIEW],
};

export function canTransition(from: string, to: string): boolean {
  if (from === to) return true; // idempotent self-transition allowed
  return (TRANSITIONS[from] ?? []).includes(to as SyncState);
}

export const TERMINAL_SYNC_STATES: SyncState[] = [SYNC_STATE.COMPLETED, SYNC_STATE.MANUAL_REVIEW];
